In [1]:
import numpy as np
import sympy as sp
from sympy.abc import z, t, k
from scipy.linalg import null_space
import scipy as sc

In [55]:
x = [1.0, 1.1, 1.3, 1.5, 1.9, 2.1]
y = [1.84, 1.96, 2.21, 2.45, 2.94, 3.18]

In [72]:
#create design matrix for polynomial of degree 2
A = np.array([[1, x[i], x[i]**2] for i in range(len(x))])
print("design matrix A = ")
print(A)

#find A^T A
ATA = A.T.dot(A)
print("A^T A = ")
print(ATA)

#find A A^T
AAT = A.dot(A.T)
print("A A^T = ")
print(AAT)

#find eigenvalues of A^T A
M = sp.Matrix(ATA) - sp.eye(3)*sp.Symbol('l')
print("ATA - lambda*I = ")
print(M)

#find determinant of M
print("det(ATA - lambda*I) = ")
print(M.det())

#find eigenvalues of A^T A
l1 = sp.roots(M.det(), sp.Symbol('l'))
l1 = list(l1.keys())[::-1]
print("Eigenvalues of A^T A = ")
print(l1)

design matrix A = 
[[1.   1.   1.  ]
 [1.   1.1  1.21]
 [1.   1.3  1.69]
 [1.   1.5  2.25]
 [1.   1.9  3.61]
 [1.   2.1  4.41]]
A^T A = 
[[ 6.      8.9    14.17  ]
 [ 8.9    14.17   24.023 ]
 [14.17   24.023  42.8629]]
A A^T = 
[[ 3.      3.31    3.99    4.75    6.51    7.51  ]
 [ 3.31    3.6741  4.4749  5.3725  7.4581  8.6461]
 [ 3.99    4.4749  5.5461  6.7525  9.5709 11.1829]
 [ 4.75    5.3725  6.7525  8.3125 11.9725 14.0725]
 [ 6.51    7.4581  9.5709 11.9725 17.6421 20.9101]
 [ 7.51    8.6461 11.1829 14.0725 20.9101 24.8581]]
ATA - lambda*I = 
Matrix([[6.0 - l, 8.90000000000000, 14.1700000000000], [8.90000000000000, 14.17 - l, 24.0230000000000], [14.1700000000000, 24.0230000000000, 42.8629 - l]])
det(ATA - lambda*I) = 
-l**3 + 63.0329*l**2 - 92.461264*l + 0.452759999999671
Eigenvalues of A^T A = 
[61.5303253733230, 1.49766141814105, 0.00491320853597199]


In [57]:
#find singular values of A
s = [sp.sqrt(l) for l in l1]
#construct S
S = np.zeros((6,3))
S[:3,:3] = np.diag(s)
S

array([[7.84412681, 0.        , 0.        ],
       [0.        , 1.22378978, 0.        ],
       [0.        , 0.        , 0.07009428],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ]])

In [73]:
#find eigendecomposition of A^T A
_, V = np.linalg.eig(ATA)
print("V = ")
print(V)

#find eigendecomposition of A A^T
_, U = np.linalg.eig(AAT)
print("U = ")
print(U)

V = 
[[-0.28829799 -0.76839176  0.57136536]
 [-0.47570216 -0.40292422 -0.78189483]
 [-0.83101848  0.49721845  0.24936338]]
U = 
[[-0.20333922 -0.55082788  0.55402391  0.15794226  0.35442072  0.10469695]
 [-0.23165137 -0.49843044  0.18561763  0.02121437 -0.70682728 -0.3778303 ]
 [-0.29463216 -0.36925792 -0.33774238 -0.6958668   0.34335437  0.2285068 ]
 [-0.36608827 -0.20758188 -0.57649901  0.66950724  0.20739673  0.37054581]
 [-0.53442645  0.21328077 -0.20020211 -0.19980875 -0.41078521 -0.71234637]
 [-0.63130852  0.47246737  0.41485141  0.04701169  0.21244068  0.3864271 ]]


In [59]:
U@S@V.T

array([[1.  , 1.  , 1.  ],
       [1.  , 1.1 , 1.21],
       [1.  , 1.3 , 1.69],
       [1.  , 1.5 , 2.25],
       [1.  , 1.9 , 3.61],
       [1.  , 2.1 , 4.41]])

In [60]:
print("solution to the least squares problem: ")
V@(np.linalg.inv(S.T@S))@S.T@U.T@y

solution to the least squares problem: 


array([ 0.59658071,  1.25329314, -0.01085343])

### Check if the solution is correct using inbuilt function

In [12]:
#find singular value decomposition of A
U1, S0, V1 = np.linalg.svd(A)
print(U1)
print(S0)
print(V1)

#construct S1
S1 = np.zeros((6,3))
S1[:3,:3] = np.diag(S0)
S1

[[-0.20333922  0.55082788  0.55402391  0.03908622 -0.18753406 -0.55821372]
 [-0.23165137  0.49843044  0.18561763  0.18776204  0.51861952  0.59935803]
 [-0.29463216  0.36925792 -0.33774238 -0.71191692 -0.3399974   0.2008647 ]
 [-0.36608827  0.20758188 -0.57649901  0.63672975 -0.27515892 -0.09695788]
 [-0.53442645 -0.21328077 -0.20020211 -0.21630593  0.62380611 -0.43919982]
 [-0.63130852 -0.47246737  0.41485141  0.06464485 -0.33973525  0.29414869]]
[7.84412681 1.22378978 0.07009428]
[[-0.28829799 -0.47570216 -0.83101848]
 [ 0.76839176  0.40292422 -0.49721845]
 [ 0.57136536 -0.78189483  0.24936338]]


array([[7.84412681, 0.        , 0.        ],
       [0.        , 1.22378978, 0.        ],
       [0.        , 0.        , 0.07009428],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ]])

In [13]:
U1@S1@V1

array([[1.  , 1.  , 1.  ],
       [1.  , 1.1 , 1.21],
       [1.  , 1.3 , 1.69],
       [1.  , 1.5 , 2.25],
       [1.  , 1.9 , 3.61],
       [1.  , 2.1 , 4.41]])

In [15]:
V1.T@(np.linalg.inv(S1.T@S1))@S1.T@U1.T@y

array([ 0.59658071,  1.25329314, -0.01085343])

## Find the least squares solution for polynomial of degree 3

In [61]:
B = np.array([[1, x[i], x[i]**2, x[i]**3] for i in range(len(x))])
print("design matrix B = ")
print(B)

design matrix B = 
[[1.    1.    1.    1.   ]
 [1.    1.1   1.21  1.331]
 [1.    1.3   1.69  2.197]
 [1.    1.5   2.25  3.375]
 [1.    1.9   3.61  6.859]
 [1.    2.1   4.41  9.261]]


In [75]:
# find SVD of B
U2, S2, V2 = np.linalg.svd(B)

print("U2 = ")
print(U2)

print("S2 = ")
print(S2)

print("V2 = ")
print(V2)


U2 = 
[[-0.11608603 -0.51462363  0.5691128  -0.43786621 -0.38108192 -0.2466717 ]
 [-0.14361447 -0.50358556  0.2663253   0.18450951  0.53530599  0.57814448]
 [-0.21244104 -0.44812067 -0.23847487  0.48499575  0.18060039 -0.6552473 ]
 [-0.3019628  -0.33992294 -0.54961907  0.03858126 -0.57359113  0.40086711]
 [-0.55430303  0.07410078 -0.30634976 -0.63677614  0.41779247 -0.11564016]
 [-0.72272702  0.39964163  0.39035867  0.36336784 -0.1790258   0.03854757]]
S2 = 
[1.45068078e+01 2.08490854e+00 1.98760092e-01 8.68328133e-03]
V2 = 
[[-0.14139116 -0.24637274 -0.44920712 -0.84706669]
 [-0.63912175 -0.56643737 -0.2955474   0.42816332]
 [ 0.66086235 -0.17451522 -0.66784011  0.29460989]
 [-0.36714151  0.76680741 -0.51463997  0.11117195]]


In [67]:
#construct S2
S0 = np.zeros((6,4))
S0[:4,:4] = np.diag(S2)
S0

array([[1.45068078e+01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 2.08490854e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.98760092e-01, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 8.68328133e-03],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [74]:
# find solution to the least squares problem
w3 = V2.T@(np.linalg.inv(S0.T@S0))@S0.T@U2.T@y
w3

array([ 0.62901928,  1.1850098 ,  0.03533252, -0.01004723])

In [71]:
#find norm of the residual
np.linalg.norm(B@w3 - y)

0.004172206964212411